FORMAT: 1A
HOST: https://kratos.website

# Kratos API

Kratos API documentation.

## Group Root

## Kratos API Root [/]

This resource does not have any attributes. Instead it offers a short welcome message.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "Welcome to the Kratos API!"
        }

## Group User

Resources related users, on-boarding, and registration.

## Register [/api/registrations]

Register and modify user's information.

### Create A New User Registration [POST]

+ Request (application/json)

    + Attributes(object)

        + user
            + phone: `1234567890` (number, required)
            + password: `password` (string, required)
            + apn_token: `<ce8be627 2e43e855 16033e24 b4c28922 0eeda487 9c477160 b2545e95 b68b5969>` (string)
            + first_name: `Eric` (string)
            + last_name: `Andre` (string)
            + address: `700 Ranch` (string)
            + city: `Brooklyn` (string)
            + state: `NY` (string)
            + zip: `11211` (number)
            + party: `Democrat` (string)
            + birthday: `2001-03-11` (string)

+ Response 200 (application/json)

            {
              "user": {
                "zip": 11211,
                "state": "NY",
                "phone": 1234567890,
                "last_name": "Andre",
                "id": 4,
                "first_name": "Eric",
                "district": 7,
                "city": "Brooklyn",
                "address": "700 Ranch"
                "party": "Democrat",
                "birthday": "2001-03-11",
                "apn_token": "<ce8be627 2e43e855 16033e24 b4c28922 0eeda487 9c477160 b2545e95 b68b5969>"
              },
              "token": "eyJhbGciOiguyagiuafhkugafI6IkpXVCJ9.eygiluafglafhufaleHAiOjE0NzU5ODk1NjMsImlhdCI6MTQ3MzM5NzU2MywiaXNzIjoiS3JhdG9zQXBpRGV2IiwianRpIjoiYmI2NjY1YjEtMjFlMi00YjFkLTlmMzEtY2U5NWU3NTdmMWNjIiwicGVtIahdgjghjkafbhjafwIjoidG9rZW4ifQ.y5oGphNTemlGLU3xhnPc5qplkLLK5hw2RmIZrbm_pc-ThjkafjkafnjlYOMpNcNVhcfJzQZjwY3o3BJUUfhYA"
            }

## Login [/api/login]

Login and existing user and start a session.

### Login & Create a New Session [POST]

+ Request (application/json)

    + Attributes(object)

        + session
            + phone: `1234567890` (number, required)
            + password: `password` (string, required)

+ Response 200 (application/json)

            {
              "user": {
                "zip": 11211,
                "state": "NY",
                "phone": 1234567890,
                "last_name": "Andre",
                "id": 4,
                "first_name": "Eric",
                "district": 7,
                "city": "Brooklyn",
                "address": "700 Ranch",
                "party": "Democrat",
                "birthday": "2001-03-11",
                "apn_token": "<ce8be627 2e43e855 16033e24 b4c28922 0eeda487 9c477160 b2545e95 b68b5969>"
              },
              "token": "eyJhbGciOiguyagiuafhkugafI6IkpXVCJ9.eygiluafglafhufaleHAiOjE0NzU5ODk1NjMsImlhdCI6MTQ3MzM5NzU2MywiaXNzIjoiS3JhdG9zQXBpRGV2IiwianRpIjoiYmI2NjY1YjEtMjFlMi00YjFkLTlmMzEtY2U5NWU3NTdmMWNjIiwicGVtIahdgjghjkafbhjafwIjoidG9rZW4ifQ.y5oGphNTemlGLU3xhnPc5qplkLLK5hw2RmIZrbm_pc-ThjkafjkafnjlYOMpNcNVhcfJzQZjwY3o3BJUUfhYA"
            }

## Me [/api/me]

Get information on the current user based on the session.

### Current User information [GET]

+ Request (application/json)
    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)

            {
              "zip": 11211,
              "state": "NY",
              "phone": 1234567890,
              "last_name": "Andre",
              "id": 4,
              "first_name": "Eric",
              "district": 7,
              "city": "Brooklyn",
              "address": "700 Ranch",
              "party": "Democrat",
              "birthday": "2001-03-11",
              "apn_token": "<ce8be627 2e43e855 16033e24 b4c28922 0eeda487 9c477160 b2545e95 b68b5969>"
            }

## My Voting Record [/api/me/votes]

List the current user's voting record and create new votes.

### View Voting Record [GET]

+ Request (application/json)
    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)

            {
              "pagination": [
                {
                  "url": "/api/me/votes?page=1",
                  "page": 1,
                  "label": "1",
                  "current": true
                }
              ],
              "data": {
                "voting_record": [
                  {
                    "value": "Nay",
                    "tally": {
                      "type": "On Motion to Suspend the Rules and Pass",
                      "treaty": null,
                      "subject": "Intelligence Authorization Act for Fiscal Year 2017",
                      "session": "2016",
                      "result_text": "Passed",
                      "result": "Passed",
                      "requires": "2/3",
                      "record_updated_at": null,
                      "question": "On Motion to Suspend the Rules and Pass: H R 6393 Intelligence Authorization Act for Fiscal Year 2017",
                      "number": 593,
                      "id": 1,
                      "date": "2016-11-30T18:47:00",
                      "chamber": "House",
                      "category": "passage-suspension",
                      "amendment": null
                    },
                    "id": 1
                  }
                ]
              }
            }

### Create new Vote [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer <token>

    + Attributes(object)

        + vote
            + tally_id: `420` (number, required)
            + value: `Aye` (string, required)

+ Response 200 (application/json)

            {
              "value": "Aye",
              "tally": {
                "type": "On the Cloture Motion",
                "treaty": null,
                "subject": "Upon Reconsideration Motion to Invoke Cloture on the Motion to Proceed to H.R. 5293",
                "session": "2016",
                "result_text": "Cloture on the Motion to Proceed Rejected (55-42, 3/5 majority required)",
                "result": "Cloture on the Motion to Proceed Rejected",
                "requires": "3/5",
                "record_updated_at": null,
                "question": "On Cloture on the Motion to Proceed H.R. 5293",
                "number": 133,
                "id": 420,
                "date": "2016-07-14T12:46:00",
                "chamber": "Senate",
                "category": "cloture",
                "amendment": null
              },
              "id": 3
            }

## My Individual Votes [/api/me/votes/{id}]

Read, update, & destroy the current user's individual votes.

### View Vote [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer <token>

+ Parameters

    + id: `3` (number, required) - individual vote database ID.

+ Response 200 (application/json)

            {
              "value": "Aye",
              "tally": {
                "type": "On the Cloture Motion",
                "treaty": null,
                "subject": "Upon Reconsideration Motion to Invoke Cloture on the Motion to Proceed to H.R. 5293",
                "session": "2016",
                "result_text": "Cloture on the Motion to Proceed Rejected (55-42, 3/5 majority required)",
                "result": "Cloture on the Motion to Proceed Rejected",
                "requires": "3/5",
                "record_updated_at": null,
                "question": "On Cloture on the Motion to Proceed H.R. 5293",
                "number": 133,
                "id": 420,
                "date": "2016-07-14T12:46:00",
                "chamber": "Senate",
                "category": "cloture",
                "amendment": null
              },
              "id": 3
            }

### Update a Vote [PUT]

+ Request (application/json)

    + Headers

            Authorization: Bearer <token>

    + Attributes(object)

        + vote
            + value: `Nay` (string, required)

+ Parameters

    + id: `3` (number, required) - individual vote database ID.

+ Response 200 (application/json)

            {
              "value": "Nay",
              "tally": {
                "type": "On the Cloture Motion",
                "treaty": null,
                "subject": "Upon Reconsideration Motion to Invoke Cloture on the Motion to Proceed to H.R. 5293",
                "session": "2016",
                "result_text": "Cloture on the Motion to Proceed Rejected (55-42, 3/5 majority required)",
                "result": "Cloture on the Motion to Proceed Rejected",
                "requires": "3/5",
                "record_updated_at": null,
                "question": "On Cloture on the Motion to Proceed H.R. 5293",
                "number": 133,
                "id": 420,
                "date": "2016-07-14T12:46:00",
                "chamber": "Senate",
                "category": "cloture",
                "amendment": null
              },
              "id": 3
            }

### Delete a Vote [DELETE]

+ Request (application/json)

    + Headers

            Authorization: Bearer <token>

+ Parameters

    + id: `3` (number, required) - individual vote database ID.

+ Response 200 (application/json)

            {
              "ok":true
            }

## Group Districts

Resources related congressional districts.

## Show District [/api/districts/{state}/{id}]

Find information and representatives for a congressional district.

### Show Congressional District [GET]

+ Request (application/json)
    + Headers

            Authorization: Bearer <token>

+ Parameters

    + state: `NY` (string, required) - state abbreviation.
    + id: `7` (number, required) - number for the congressional district.

+ Response 200 (application/json)

            {
              "pagination": [
                {
                  "url": "/api/districts/NY/7?id=7&page=1&state=NY",
                  "page": 1,
                  "label": "1",
                  "current": true
                }
              ],
              "data": [
                {
                  "youtubeid": "SenatorSchumer",
                  "twitterid": "SenSchumer",
                  "sortname": "Schumer, Charles “Chuck” (Sen.) [D-NY]",
                  "roles": [
                    {
                      "website": "https://www.schumer.senate.gov",
                      "title_long": "Senator",
                      "title": "Sen.",
                      "state": "NY",
                      "startdate": "2011-01-05",
                      "senator_rank_label": "Senior",
                      "senator_rank": "senior",
                      "senator_class_label": "Class 3",
                      "senator_class": "class3",
                      "role_type_label": "Senator",
                      "role_type": "senator",
                      "phone": "202-224-6542",
                      "party": "Democrat",
                      "leadership_title": null,
                      "id": 19,
                      "govtrack_id": 4282,
                      "extra": {
                        "office": "322 Hart Senate Office Building",
                        "fax": "202-228-3027",
                        "contact_form": "http://www.schumer.senate.gov/Contact/email-chuck",
                        "address": "322 Hart Senate Office Building Washington DC 20510"
                      },
                      "enddate": "2017-01-03",
                      "district": null,
                      "description": "Senior Senator from New York",
                      "current": true,
                      "caucus": null
                    }
                  ],
                  "pvsid": "26976",
                  "osid": "N00001093",
                  "nickname": "Chuck",
                  "namemod": null,
                  "name": "Sen. Charles “Chuck” Schumer [D-NY]",
                  "middlename": "E.",
                  "link": "https://www.govtrack.us/congress/members/charles_schumer/300087",
                  "lastname": "Schumer",
                  "image_url": "https://theunitedstates.io/images/congress/225x275/S000148.jpg",
                  "id": 19,
                  "govtrack_id": 300087,
                  "gender_label": "Male",
                  "gender": "male",
                  "firstname": "Charles",
                  "current_state": "NY",
                  "current_party": "D",
                  "cspanid": 5929,
                  "birthday": "1950-11-23",
                  "bioguideid": "S000148"
                },
              ]
            }

## Group Representatives

Information related congressional representatives.

## Representative [/api/representatives/{id}/votes]

### Get Voting Record [GET]

+ Request (application/json)
    + Headers

            Authorization: Bearer <token>

+ Parameters
    + id: `412223` (number, required) - representative's PERSON ID.

+ Response 200 (application/json)

            {
              "pagination": [
                {
                  "url": "/api/representatives/19/votes?id=19&page=1",
                  "page": 1,
                  "label": "1",
                  "current": true
                },
                {
                  "url": "/api/representatives/19/votes?id=19&page=2",
                  "page": 2,
                  "label": "Next",
                  "current": false
                }
              ],
              "data": {
                "voting_record": [
                  {
                  "value": "Nay",
                  "tally": {
                    "type": "On the Cloture Motion",
                    "treaty": null,
                    "subject": "Motion to Invoke Cloture on the Motion to Concur in the House Amendment to the Senate Amendment to H.R. 2028",
                    "session": "2016",
                    "result_text": "Cloture Motion Agreed to (61-38, 3/5 majority required)",
                    "result": "Cloture Motion Agreed to",
                    "requires": "3/5",
                    "record_updated_at": null,
                    "question": "On the Cloture Motion H.R. 2028",
                    "number": 160,
                    "id": 158,
                    "date": "2016-12-09T22:00:00",
                    "chamber": "Senate",
                    "category": "cloture",
                    "amendment": null
                  },
                  "id": 56682
                  },
                ]
              }
            }

## Group Tallies

Resources related congressional tallies (votes & questions on Bills).

## Tally [/api/tallies/{id}]

### Get Detailed Tally Information [GET]

+ Request
    + Headers

            Authorization: Bearer <token>

+ Parameters
    + id: `201` (number, required) - tallies' TALLY ID.

+ Response 200 (application/json)

              {
                "Not Voting": 14,
                "No": 162,
                "Aye": 254,
                "votes": [
                  {
                    "value": "Not Voting",
                    "person": {
                      "lastname": "Sanchez",
                      "image": "https://theunitedstates.io/images/congress/225x275/S000030.jpg",
                      "id": 192,
                      "firstname": "Loretta",
                      "current_state": "CA46",
                      "current_party": "D"
                    },
                    "id": 72083
                  },
                  {
                    "value": "No",
                    "person": {
                      "lastname": "Wasserman Schultz",
                      "image": "https://theunitedstates.io/images/congress/225x275/W000797.jpg",
                      "id": 226,
                      "firstname": "Debbie",
                      "current_state": "FL23",
                      "current_party": "D"
                    },
                    "id": 72065
                  },
                  {
                    "value": "Aye",
                    "person": {
                      "lastname": "Yoho",
                      "image": "https://theunitedstates.io/images/congress/225x275/Y000065.jpg",
                      "id": 418,
                      "firstname": "Ted",
                      "current_state": "FL3",
                      "current_party": "R"
                    },
                    "id": 71903
                  },
                ],
                "type": "On Passage of the Bill",
                "treaty": null,
                "subject": "To provide for the prohibition on cash payments to the Government of Iran, and for other purposes",
                "source_url": "http://clerk.house.gov/evs/2016/roll554.xml",
                "session": "2016",
                "result_text": "Passed",
                "result": "Passed",
                "requires": "1/2",
                "record_updated_at": null,
                "question": "On Passage: H R 5931 To provide for the prohibition on cash payments to the Government of Iran, and for other purposes",
                "number": 554,
                "id": 201,
                "gpo_id": "h554-114.2016",
                "date": "2016-09-22T21:19:00",
                "chamber": "House",
                "category": "passage",
                "bill_id": 7529,
                "amendment": null
              }


## Group Bills

Resources related congressional bills & resolutions.

## Bill [/api/bills/{id}]

### Get Detailed Bill Information [GET]

+ Request
    + Headers

            Authorization: Bearer <token>

+ Parameters
    + id: `7141` (number, required) - bill's BILL ID.

+ Response 200 (application/json)

            {
              "vetoed": false,
              "urls": null,
              "type": "s",
              "top_term": "Armed forces and national security",
              "titles": [
                {
                  "type": "display",
                  "title": "National Defense Authorization Act for Fiscal Year 2017",
                  "is_for_portion": false,
                  "as": null
                }
              ],
              "tallies": [
                {
                  "Yea": 70,
                  "Not Voting": 1,
                  "Nay": 10,
                  "votes": [
                    {
                      "value": "Yea",
                      "person_lastname": "Wicker",
                      "person_image": "https://theunitedstates.io/images/congress/225x275/W000437.jpg",
                      "person_firstname": "Roger",
                      "person_current_state": "MS",
                      "person_current_party": "R",
                      "id": 19133
                    },
                    {
                      "value": "Nay",
                      "person_lastname": "Gillibrand",
                      "person_image": "https://theunitedstates.io/images/congress/225x275/G000555.jpg",
                      "person_firstname": "Kirsten",
                      "person_current_state": "NY",
                      "person_current_party": "D",
                      "id": 19054
                    },
                  ],
                  "type": "On Passage of the Bill",
                  "treaty": null,
                  "subject": "S. 2943 As Amended",
                  "source_url": "http://www.senate.gov/legislative/LIS/roll_call_votes/vote1142/vote_114_2_00098.xml",
                  "session": "2016",
                  "result_text": "Bill Passed (85-13)",
                  "result": "Bill Passed",
                  "requires": "1/2",
                  "record_updated_at": null,
                  "question": "On Passage of the Bill S. 2943",
                  "number": 98,
                  "id": 51,
                  "gpo_id": "s98-114.2016",
                  "date": "2016-06-14T11:04:00",
                  "chamber": "Senate",
                  "category": "passage",
                  "amendment": null
                },
                {
                  "Yea": 395,
                  "Not Voting": 21,
                  "Nay": 14,
                  "votes": [
                    {
                      "value": "Nay",
                      "person_lastname": "Amash",
                      "person_image": "https://theunitedstates.io/images/congress/225x275/A000367.jpg",
                      "person_firstname": "Justin",
                      "person_current_state": "MI3",
                      "person_current_party": "R",
                      "id": 43894
                    }
                  ],
                  "type": "On Closing Portions of the Conference",
                  "treaty": null,
                  "subject": "National Defense Authorization Act for Fiscal Year 2017",
                  "source_url": "http://clerk.house.gov/evs/2016/roll400.xml",
                  "session": "2016",
                  "result_text": "Passed",
                  "result": "Passed",
                  "requires": "1/2",
                  "record_updated_at": null,
                  "question": "On Closing Portions of the Conference: S 2943 National Defense Authorization Act for Fiscal Year 2017",
                  "number": 400,
                  "id": 121,
                  "gpo_id": "h400-114.2016",
                  "date": "2016-07-08T12:08:00",
                  "chamber": "House",
                  "category": "unknown",
                  "amendment": null
                }
              ],
              "summary_text": "Highlights: This bill authorizes FY2017 appropriations and sets forth policies regarding the military activities of the Department of Defense (DOD), military construction, and the national security programs of the Department of Energy (DOE).The bill authorizes appropriations, but does not provide budget authority, which is provided by appropriations legislation.The bill authorizes appropriations to DOD for: Procurement; Research, Development, Test, and Evaluation; Operation and Maintenance; Cooperative Threat Reduction; Working Capital Funds; the National Defense Sealift Fund; Chemical Agents and Munitions Destruction; Defense-Wide Drug Interdiction and Counter-Drug Activities; the Defense Inspector General; the Defense Health Program; and the National Sea-Based Deterrence Fund. The bill also authorizes appropriations for Overseas Contingency Operations (OCO) . . . ",
              "summary_date": "2016-07-07T12:10:06",
              "subjects": [
                "National and community service",
              ],
              "status_at": null,
              "status": "PASSED:BILL",
              "sponsor": {
                "youtubeid": "SenatorJohnMcCain",
                "twitterid": "SenJohnMcCain",
                "sortname": "McCain, John (Sen.) [R-AZ]",
                "roles": [
                  {
                    "website": "http://www.mccain.senate.gov",
                    "title_long": "Senator",
                    "title": "Sen.",
                    "state": "AZ",
                    "startdate": "2011-01-05",
                    "senator_rank_label": "Senior",
                    "senator_rank": "senior",
                    "senator_class_label": "Class 3",
                    "senator_class": "class3",
                    "role_type_label": "Senator",
                    "role_type": "senator",
                    "phone": "202-224-2235",
                    "party": "Republican",
                    "leadership_title": null,
                    "id": 14,
                    "govtrack_id": 4190,
                    "extra": {
                      "office": "218 Russell Senate Office Building",
                      "fax": "202-228-2862",
                      "contact_form": "http://www.mccain.senate.gov/public/index.cfm/contact-form",
                      "address": "218 Russell Senate Office Building Washington DC 20510"
                    },
                    "enddate": "2017-01-03",
                    "district": null,
                    "description": "Senior Senator from Arizona",
                    "current": true,
                    "caucus": null
                  }
                ],
                "pvsid": "53270",
                "osid": "N00006424",
                "nickname": null,
                "namemod": null,
                "name": "Sen. John McCain [R-AZ]",
                "middlename": "S.",
                "link": "https://www.govtrack.us/congress/members/john_mccain/300071",
                "lastname": "McCain",
                "image_url": "https://theunitedstates.io/images/congress/225x275/M000303.jpg",
                "id": 14,
                "govtrack_id": 300071,
                "gender_label": "Male",
                "gender": "male",
                "firstname": "John",
                "current_state": "AZ",
                "current_party": "R",
                "cspanid": 7476,
                "birthday": "1936-08-29",
                "bioguideid": "M000303"
              },
              "short_title": "National Defense Authorization Act for Fiscal Year 2017",
              "related_bills": [
                {
                  "related_bill_id": 74,
                  "reason": "related"
                },
              ],
              "popular_title": null,
              "official_title": "An original bill to authorize appropriations for fiscal year 2017 for military activities of the Department of Defense, for military construction, and for defense activities of the Department of Energy, to prescribe military personnel strengths for such fiscal year, and for other purposes.",
              "number": "2943",
              "introduced_at": "2016-05-18",
              "id": 784,
              "history": {
                "vetoed": false,
                "senate_passage_result_at": "2016-12-08",
                "senate_passage_result": "pass",
                "senate_cloture_result_at": "2016-05-25",
                "senate_cloture_result": "pass",
                "house_passage_result_at": "2016-12-02T11:37:54-05:00",
                "house_passage_result": "pass",
                "enacted": false,
                "awaiting_signature_since": "2016-12-14",
                "awaiting_signature": true,
                "active_at": "2016-05-18",
                "active": true
              },
              "gpo_id": "s2943-114",
              "gpo_data_updated_at": "2016-12-16T09:56:36",
              "enacted_as": null,
              "enacted": false,
              "cosponsors": [],
              "congress_number": 114,
              "committees": [
                {
                  "url": "http://armed-services.senate.gov/",
                  "sub_committees": [],
                  "parent": [],
                  "obsolete": false,
                  "name": "Senate Committee on Armed Services",
                  "jurisdiction_link": null,
                  "jurisdiction": null,
                  "id": 11,
                  "govtrack_id": 2594,
                  "committee_type_label": "Senate",
                  "committee_type": "senate",
                  "code": "SSAS",
                  "abbrev": "ArmServs"
                }
              ],
              "committee_history": [
                {
                  "committee_id": "SSAS",
                  "committee": "Senate Armed Services",
                  "activity": [
                    "origin",
                    "reporting"
                  ]
                }
              ],
              "awaiting_signature": true,
              "amendments": [],
              "active": true,
              "actions": [
                {
                  "type": "action",
                  "text": "Introduced in Senate",
                  "references": [],
                  "action_code": "10000",
                  "acted_at": "2016-05-18"
                },
                {
                  "type": "topresident",
                  "text": "Presented to President.",
                  "references": [],
                  "action_code": "E20000",
                  "acted_at": "2016-12-14"
                }
              ]
            }
